# Generated by Django 3.0.4 on 2020-03-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('timestamp', models.FloatField()),
                ('cluster', models.TextField()),
                ('source', models.TextField()),
            ],
        ),
    ]
