# Generated by Django 3.0.4 on 2020-03-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
