# Generated by Django 3.0.4 on 2020-03-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200323_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
