# Generated by Django 3.0.4 on 2020-03-24 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200323_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
